// This page sends meal images and daily meal data to a FastAPI backend,
// where an AI analyzes the food (nutrition, ingredients, health advice)
// and returns structured results used in the app.

import 'dart:io';
import 'package:http/http.dart' as http;
import 'dart:convert';
import '../models/meal_models.dart';

class MealAnalysisService {
  ///                     use: 'http://YOUR_COMPUTER_IP:8000'
  static const String baseUrl = 'http://0.0.0.0:8000';

  /// Analyze a meal image with AI
  static Future<Map<String, dynamic>> analyzeMeal({
    /// Returns a JSON
    required String imagePath,
    required String userId,
    String? mealType,
    Map<String, dynamic>? userProfile,
  }) async {
    try {
      final uri = Uri.parse('$baseUrl/analyze-meal');
      var request = http.MultipartRequest('POST', uri);

      /// Attach image file to the request
      request.files.add(
        await http.MultipartFile.fromPath('image', imagePath),
      );

      /// Add text fields to the body
      request.fields['userId'] = userId;
      if (mealType != null) {
        request.fields['mealType'] = mealType;
      }
      if (userProfile != null) {
        request.fields['userProfile'] = jsonEncode(userProfile);
      }
      /// Force AI output to English
      request.fields['language'] = 'en';

      /// Send the HTTP request (multipart upload)
      final streamedResponse = await request.send();
      final response = await http.Response.fromStream(streamedResponse);

      if (response.statusCode == 200) {
        return jsonDecode(response.body);
      } else {
        String message = 'Error (${response.statusCode})';
        try {
          final data = jsonDecode(response.body);
          if (data is Map && data['detail'] != null) {
            message = data['detail'].toString();
          }
        } catch (_) {}
        throw Exception(message);
      }
    } catch (e) {
      throw Exception('Erreur lors de l\'analyse du repas: $e');
    }
  }

  /// Analyze the entire day of meals
  static Future<DailySummary> analyzeDailyMeals({
    /// Returns a DailySummary object (generated by the backend AI)
    required String userId,
    required DateTime date,
    required List<MealAnalysis> mealAnalyses,
  }) async {
    try {
      final uri = Uri.parse('$baseUrl/analyze-daily');

      final response = await http.post(
        uri,
        headers: {'Content-Type': 'application/json'},
        body: jsonEncode({
          'userId': userId,
          'date': date.toIso8601String(),
          'meals': mealAnalyses.map((m) => m.toJson()).toList(),
          'language': 'en',
        }),
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        return DailySummary.fromJson(data);
      } else {
        throw Exception('Error: ${response.statusCode}');
      }
    } catch (e) {
      throw Exception('Error: $e');
    }
  }
}