// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7qoiCuhwPip4gmj29AXcYVX2-10MWuIs',
    appId: '1:887667219079:web:1b166c0f00caaa131e7622',
    messagingSenderId: '887667219079',
    projectId: 'cstamapp-e3eee',
    authDomain: 'cstamapp-e3eee.firebaseapp.com',
    storageBucket: 'cstamapp-e3eee.firebasestorage.app',
    measurementId: 'G-MVR55W1LTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDypJHPbsPnNyJYCHdm_xXLuIxkvbSgHIA',
    appId: '1:887667219079:android:45e6070bdf20cf151e7622',
    messagingSenderId: '887667219079',
    projectId: 'cstamapp-e3eee',
    storageBucket: 'cstamapp-e3eee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7bOXS4EQNy2zK_CWZ_GGaGsZk1BPcbIc',
    appId: '1:887667219079:ios:7244b4fa15698f3c1e7622',
    messagingSenderId: '887667219079',
    projectId: 'cstamapp-e3eee',
    storageBucket: 'cstamapp-e3eee.firebasestorage.app',
    iosBundleId: 'com.example.cstamapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7bOXS4EQNy2zK_CWZ_GGaGsZk1BPcbIc',
    appId: '1:887667219079:ios:7244b4fa15698f3c1e7622',
    messagingSenderId: '887667219079',
    projectId: 'cstamapp-e3eee',
    storageBucket: 'cstamapp-e3eee.firebasestorage.app',
    iosBundleId: 'com.example.cstamapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7qoiCuhwPip4gmj29AXcYVX2-10MWuIs',
    appId: '1:887667219079:web:2845c5cf837b786b1e7622',
    messagingSenderId: '887667219079',
    projectId: 'cstamapp-e3eee',
    authDomain: 'cstamapp-e3eee.firebaseapp.com',
    storageBucket: 'cstamapp-e3eee.firebasestorage.app',
    measurementId: 'G-HRMH2G8TQW',
  );
}
